import Head from 'next/head'
import Activities from '../components/Activities'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Listings from '../components/Listings'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <Activities />
      <Listings />
      <Footer />
    </div>
  )
}
